### ISSUE TITLE
Site search broken with iteritems error

### ISSUE THREAD

**Issue by brew** [okfn/rtei#33]
Performing a search on the site returns an Internal Error. Logs have a stack trace:

```
2019-01-14T11:50:22.142431+00:00 app[web.1]: Internal Server Error: /en/search/
2019-01-14T11:50:22.142445+00:00 app[web.1]: Traceback (most recent call last):
2019-01-14T11:50:22.142447+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
2019-01-14T11:50:22.142449+00:00 app[web.1]:     response = get_response(request)
2019-01-14T11:50:22.142451+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
2019-01-14T11:50:22.142452+00:00 app[web.1]:     response = self._get_response(request)
2019-01-14T11:50:22.142454+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
2019-01-14T11:50:22.142456+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2019-01-14T11:50:22.142457+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
2019-01-14T11:50:22.142459+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2019-01-14T11:50:22.142462+00:00 app[web.1]:   File "/app/search/views.py", line 34, in search
2019-01-14T11:50:22.142464+00:00 app[web.1]:     for code, name in get_countries_with_data().iteritems():
2019-01-14T11:50:22.142471+00:00 app[web.1]: AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'
```

This is a Py2 -> Py3 issues that must have been missed with the 2to3 tool. Run again, and catch other instances of the issue.

**Comment by brew** [comment]
Fixed in 1d9197ab65a435328a741ccd2132f03e4f4dc084
